name: Build docs
on:
  release:
    types:
      - created

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Documentation build
        uses: johannes-huther/webhook.sh@v1.0.0
        with:
          webhook_url: ${{ secrets.DOC_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.DOC_TOKEN }}
      - name: API ref build
        uses: johannes-huther/webhook.sh@v1.0.0
        with:
          webhook_url: ${{ secrets.APIREF_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.APIREF_TOKEN }}
